# These are supported funding model platforms

patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: themens
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: themens/carnage
#custom: ['https://www.paypal.com/donate?hosted_button_id=62BBB32FGRB2A', 'https://mpago.la/2rHzU1b']
